language:
    java

sudo:
    false

dist: trusty

jdk:
    - oraclejdk8
    - oraclejdk9
    - openjdk7

matrix:
    allow_failures:
        - jdk: oraclejdk9

before_script:
  - git submodule update --remote --recursive

script:
  - cd sample-code-java
  - mvn install -DsdkVersion=2.0.1-SNAPSHOT -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -DsdkVersion=2.0.1-SNAPSHOT -B

after_script:
    print_surefire_reports.sh
 
